name = "vhlink"
type = "javascript"
account_id = "39a76d640a29996bffbd58c36a537c2b"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "9deaabf5f0434fe0883e5b2f5c6b31fa", preview_id = "79deaabf5f0434fe0883e5b2f5c6b31fa" }
]
